---
- name: i3 Configuration
  hosts: localhost

  vars:
    i3_config_dir: "/home/{{ user.account }}/.config/i3"

  tasks:
    - name: i3
      become: true
      dnf:
        name:
          - i3
        state: present

    - name: i3 config directory
      file:
        path: "{{ i3_config_dir }}"
        state: directory

    - name: i3 config
      copy:
        src: files/i3.vmware.config
        dest: "{{ i3_config_dir }}/config"
        owner: "{{ user.account }}"
        group: "{{ user.account }}"
        mode: 0664
