---
- name: Java Development Configuration
  hosts: localhost
  become: true

  tasks:
    - name: jdk 11
      dnf:
        name:
          - java-11-openjdk
          - java-11-openjdk-src
          - java-11-openjdk-javadoc
          - java-11-openjdk-devel
        state: latest

  roles:
    - name: sdkman (maven, gradle)
      role: sdkman
      sdkman_user: "{{ user.account }}"
      sdkman_group: "{{ user.account }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: maven, version: "3.6.0" }
        - { candidate: gradle, version: "5.3" }
