---
- name: Angular Development Configuration
  hosts: localhost
  become: true

  vars:
    node_version: "10"

  tasks:
    - name: "add nodesource {{ node_version }} repository"
      copy:
        src: "files/nodesource-el7-pub_{{ node_version }}.x.repo"
        dest: "/etc/yum.repos.d/nodesource-el7.repo"
        mode: 0664
      notify: remove old nodejs

    - name: add yarn repository
      get_url:
        url: "https://dl.yarnpkg.com/rpm/yarn.repo"
        checksum: sha256:f082589ae243fdaaaec735c7cb898624f57d9f93b77e1be259955b678fcde664
        dest: "/etc/yum.repos.d/yarn.repo"
        mode: 0664
      notify: remove old yarn

    - meta: flush_handlers

    - name: install yarn and nodejs
      dnf:
        name:
          - yarn
          - nodejs
        state: present

  handlers:
    - name: remove old nodejs
      dnf:
        name: nodejs
        state: absent

    - name: remove old yarn
      dnf:
        name: yarn
        state: absent
