---
- name: Package Configuration
  hosts: localhost
  become: true

  tasks:
    - name: Install dnf
      yum:
        name:
          - dnf
          - dnf-plugins-core
        state: present

    - name: Install epel repository
      dnf:
        name: epel-release
        state: present

    - name: Install tools
      dnf:
        name:
          - docker
          - git
          - gitk
          - git-extras
          - git-gui
          - npm
          - tig
          - tmux
          - tree
          - util-linux
          - vim
          - zsh
        state: present

    - name: Install yarn
      npm:
        name:
          - yarn
        state: present
        global: yes

    - name: Uninstall nano
      dnf:
        name:
          - nano
        state: absent

  roles:
    - name: Install and configure Java 8
      role: java
      java_version: '8'
      java_vendor: adoptopenjdk
      java_is_default_installation: no
      java_fact_group_name: java_8

    - name: Install and configure Java 11
      role: java
      java_version: '11'
      java_vendor: adoptopenjdk
      java_is_default_installation: yes
      java_fact_group_name: java

    - name: Install and configure maven
      role: maven

    - name: Install and configure maven color extension
      role: maven-color

    - name: Install and configure maven notifier extension
      role: maven-notifier

    - name: Install and configure oh-my-zsh
      role: oh-my-zsh
      users:
        - username: mintdev
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - copyfile
              - dnf
              - docker
              - git
              - git-extras
              - gradle
              - mvn
              - ng
              - sudo
              - systemd
              - tig
              - yarn
              - yum
              - z
