---
- name: Git Configuration
  hosts: localhost

  vars:
    user_name: Joseph Egan
    user_email: joseph.s.egan@gmail.com

  tasks:
    - name: git tools
      become: true
      dnf:
        name:
          - git
          - git-extras
          - git-gui
          - gitk
          - tig
        state: present

    - name: global git config
      git_config:
        name: "{{ item.key }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - { key: "color.ui", value: "auto" }
        - { key: "user.name", value: "{{ user_name }}" }
        - { key: "user.email", value: "{{ user_email }}" }
        - { key: "alias.gl", value: "log --graph --decorate --format=oneline --all" }
        - { key: "alias.ap", value: "add --patch" }
        - { key: "alias.ca", value: "commit --amend" }
        - { key: "alias.cne", value: "commit --amend --no-edit" }
        - { key: "alias.fa", value: "fetch --all --prune" }
        - { key: "alias.ff", value: "merge --ff-only" }
